slack_token: "abc"
github_token: "123"

github_orgs: |-
  {
    "organization-name": {
      "public_only": true,
      "aliases": [],
      "new_repo_teams": {
        "id": "1234567",
        "perm": "push",
        "name": "example-team-name"
      }
    }
  }