slack_token: "abc"
github_token: "123"

github_orgs: |-
  {"org-name": {
      "public_only": true,
      "aliases": [],
      "new_repo_teams": {
        "id": "1234",
        "perm": "push",
        "name": "my-cool-new-test-team" }}}