apiVersion: v1
kind: Pod
metadata:
  name: hubcommander
spec:
  containers:
    - name: hubcommander
      image: quay.io/evan_tschuy/hubcommander:latest
      env:
      - name: PYTHONUNBUFFERED
        value: "true"
      - name: SLACK_TOKEN
        valueFrom:
          secretKeyRef:
            name: hubcommander-secrets
            key: slack_token
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: hubcommander-secrets
            key: github_token
      - name: IMPLICIT_COMMAND_ENABLE
        value: "false"
      - name: ROLLCONTROL_CONFIG
        value: /rtmbot/hubcommander/config/rollcontrol.yaml
      - name: HUBCOMMANDER_ORGS
        value: /rtmbot/hubcommander/config/organizations.json
      - name: HUBCOMMANDER_USER_COMMANDS
        value: /rtmbot/hubcommander/config/user_commands.json
      volumeMounts:
      - mountPath: /rtmbot/hubcommander/config
        name: hubcommander-config
  volumes:
  - name: hubcommander-config
    configMap:
      name: hubcommander-config
