apiVersion: v1
kind: Pod
metadata:
  name: hubcommander
spec:
  containers:
    - name: hubcommander
      image: netflixoss/hubcommander:0.2.0
      env:
      - name: SLACK_TOKEN
        valueFrom:
          secretKeyRef:
            name: hubcommander-secrets
            key: slack_token
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: hubcommander-secrets
            key: github_token
      - name: ROLLCONTROL_CONFIG
        value: /rtmbot/hubcommander/auth_plugins/rollcontrol/config.yaml
      - name: HUBCOMMANDER_ORGS
        value: {{ .Values.github_orgs | quote }}
      - name: HUBCOMMANDER_USER_COMMANDS
        value: {{ .Values.user_commands | quote }}
      volumeMounts:
      - mountPath: /rtmbot/hubcommander/github/config.py
        subPath: config.py
        name: hubcommander-github-config
      - mountPath: /rtmbot/hubcommander/auth_plugins/enabled_plugins.py
        subPath: enabled_plugins.py
        name: hubcommander-auth-plugins
      - mountPath: /rtmbot/hubcommander/auth_plugins/rollcontrol
        name: hubcommander-rollcontrol
  volumes:
  - name: hubcommander-github-config
    configMap:
      name: hubcommander-config
  - name: hubcommander-rollcontrol
    configMap:
      name: hubcommander-rollcontrol
  - name: hubcommander-auth-plugins
    configMap:
      name: hubcommander-auth-plugins