apiVersion: v1
kind: Pod
metadata:
  name: hubcommander
spec:
  containers:
    - name: hubcommander
      image: quay.io/evan_tschuy/hubcommander:0.1.1
      env:
      - name: SLACK_TOKEN
        valueFrom:
          secretKeyRef:
            name: hubcommander-secrets
            key: slack_token
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: hubcommander-secrets
            key: github_token
      - name: ROLLCONTROL_CONFIG
        value: /rtmbot/hubcommander/auth_plugins/rollcontrol/config.yaml
      - name: HUBCOMMANDER_ORGS
        value: {{ .Values.github_orgs | quote }}
      - name: HUBCOMMANDER_USER_COMMANDS
        value: {{ .Values.user_commands | quote }}
      volumeMounts:
      - mountPath: /rtmbot/hubcommander/auth_plugins/rollcontrol/config.yaml
        subPath: config.yaml
        name: hubcommander-rollcontrol-config
  volumes:
  - name: hubcommander-rollcontrol-config
    configMap:
      name: hubcommander-rollcontrol-config