---
apiVersion: v1
kind: Secret
metadata:
  name: hubcommander-secrets
type: Opaque
data:
  slack_token: {{ .Values.slack_token | b64enc | quote }}
  github_token: {{ .Values.github_token | b64enc | quote }}