apiVersion: v1
kind: Pod
metadata:
  name: hubcommander
spec:
  containers:
    - name: hubcommander
      image: netflixoss/hubcommander:0.2.0
      env:
      - name: SLACK_TOKEN
        value: {{ .Values.slack_token }}
      - name: GITHUB_TOKEN
        value: {{ .Values.github_token }}
      - name: HUBCOMMANDER_ORGS
        value: {{ .Values.github_orgs | quote }}
      - name: HUBCOMMANDER_USER_COMMANDS
        value: {{ .Values.user_commands | quote }}
      volumeMounts:
      - mountPath: /rtmbot/hubcommander/github/config.py
        subPath: config.py
        name: hubcommander-github-config
  volumes:
  - name: hubcommander-github-config
    configMap:
      name: hubcommander-config